apiVersion: astra.netapp.io/v1
kind: Snapshot
metadata:
  generateName: ghost-snapshot-
  namespace: astra-connector
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    argocd.argoproj.io/instance: ghost-demo
spec:
  appVaultRef: astra-gcp-backup-734ced050128
  applicationRef: ghost
