apiVersion: astra.netapp.io/v1
kind: Snapshot
metadata:
  generateName: ghost-snapshot-
  namespace: astra-connector
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  appVaultRef: astra-gcp-backup-734ced050128
  applicationRef: ghost
